### ISSUE TITLE
Add a Python test harness

### ISSUE THREAD

**Issue by erikrose** [mozilla/fathom#114]
We're starting to accumulate enough branches that they're time-consuming and error-prone to test manually, especially as a 3-person team starts having to test each other's stuff redundantly during code reviews. Let's hook up at least a nearly-empty set of Python tests so it runs on CI and is triggered by `make test`. I favor pytest but am open to reasoning against. Good first proof-that-it-works tests would be for the branchy `test.decode_weights()` and the error-prone `pretty_coeffs()` (just test that its output is valid JSON).

The Travis image we're using is the Node one, so we probably don't get a lot of Python stuff for free. However, there is at least a basic Python around, as I use it to deploy the docs (see the file `travis-deploy-docs`). We'll want to not trip over that. We may need to install Python 3 ourselves. It should be…interesting. :-)

**Comment by danielhertenstein** [comment]
I also prefer pytest.

**Comment by danielhertenstein** [comment]
Closed by #120
