### ISSUE TITLE
Consider removing the slow Readability test

### ISSUE THREAD

**Issue by erikrose** [mozilla/fathom#131]
It takes 60 seconds, and we always end up either getting mad at it locally or `skip`ing it. It's not paying its rent. See what we lose, coverage-wise, by disabling or removing it. If little, or if we can add the coverage back in relatively easily, remove or disable the test.

The test I'm talking about is the `it('the Readability test suite'` one.

I think it may be the only remaining user of the Corpus Framework (Run, Corpus, and Sample classes in optimizers.mjs), which we could then remove.

**Comment by biancadanforth** [comment]
This was closed by @erikrose in PR #151 .
