### ISSUE TITLE
Provide performant implementations for common rules in the Fathom library

### ISSUE THREAD

**Issue by biancadanforth** [mozilla/fathom#146]
As Fathom is used more and more for different applications, there may be a set of common rules (e.g. `isVisible`, #118 ) that the library could provide to make developing a Fathom ruleset more convenient and executing the ruleset more performant at the same time.

**Comment by erikrose** [comment]
Absolutely! I hope to do this continually, as a side effect of factoring out repetition between rulesets. Is this really a task we can "check off" and finish, once and for all? If not, maybe we should close it. I'll do that now to save paperwork, but re-open if you disagree.
