### ISSUE TITLE
`fathom-list` with recursive flag lists HTML files in the resources directories.

### ISSUE THREAD

**Issue by danielhertenstein** [mozilla/fathom#185]
If you use `fathom-list` with the recursive flag and there are HTML files in any resource directory, those HTML files will be included in the output. This should not happen. We should change our recursive search so it does not include the resources directory.

**Comment by Dcoder99** [comment]
Hi @danielhertenstein , I'd like to work on this issue. May I know where this recursive search is defined so that I can try fixing this?

**Comment by erikrose** [comment]
Actually, I fixed this in 0bc62e70127b983c04dbf047c4fce4d5f2de1ed2. Sorry I forgot to mark it as closed! Can we interest you in any other Good First Issues?
