### ISSUE TITLE
Characterize Chrome's distraction-free-browsing mode

### ISSUE THREAD

**Issue by erikrose** [mozilla/fathom#2]
How does Chrome identify what's a distraction and what's not? Summarize on a new [ChromeDistractionFreeBrowsing](ChromeDistractionFreeBrowsing) page.

**Comment by pelmers** [comment]
Started drafting at https://github.com/mozilla/snuffy/wiki/ChromeDistractionFreeBrowsing.

I just put down an overview, I haven't really looked at the gritty details of its heuristics.

**Comment by erikrose** [comment]
Looks great! Incidentally, her source is some of the most readable C++ I've ever encountered, due to her use of modern C++ features and the low-impedance-mismatch API she's programming against.

Their approach is clearly more complicated than Readability's, but they do more as well, finding prev (not just next) buttons and "lead images". Good stuff.
