### ISSUE TITLE
How to generate documents?

### ISSUE THREAD

**Issue by 625781186** [mozilla/fathom#238]
I use `make.bat html` , 

![image](https://user-images.githubusercontent.com/30521429/82115562-1f0c2680-9796-11ea-8a6b-288d3bf448c3.png)

But I'm not found this output folder.

**Comment by erikrose** [comment]
Run `make html` in the docs folder. I recently deleted make.bat, because there's no realistic way it could have been working after all the customization we did. If that doesn't work, let me know!
