### ISSUE TITLE
Update Readbility algorithm description

### ISSUE THREAD

**Issue by erikrose** [mozilla/fathom#3]
Update [Readbility](https://github.com/mozilla/fathom/wiki/Readability#algorithm) with the changes [Mozilla made](https://github.com/mozilla/readability) to [Arc90 Labs' original work](https://github.com/baojie/arc90labs-readability).

**Comment by adentranter** [comment]
The link to Readbility is broken ( https://github.com/mozilla/fathom/issues/Readability#algorithm ) from within the first comment.
