### ISSUE TITLE
Training infra for automatic coefficient determination

### ISSUE THREAD

**Issue by cantino** [mozilla/fathom#35]
Cool project!

Have you considered ways to determine weights automatically? Once you have a set of rules, it'd be awesome to be able to learn weights by providing a set of documents with extractions and labelling them as either correct or incorrect.  This then becomes a fairly standard supervised learning problem to estimate the weights.

**Comment by erikrose** [comment]
Yes! We are at but phase 1 of Fathom. I see 3 phases:

1. Write feature extractors ourselves.
2. Write feature extractors ourselves, but tune the coefficients (scores, clustering coefficients, etc.) with a supervised training set.
3. Use deep learning to come up with increasingly higher-level features unsupervised, and just have humans attach semantics to them.

As you guessed, there is a reason for representing rulesets as manipulable data as much as possible. :-) I'm not going to get to phase 2 for awhile. Would you be interested in building some of the training machinery?

**Comment by cantino** [comment]
Sorry for the delay. I'm definitely interested in seeing this project progress, but likely don't have time to contribute in the short term.

**Comment by erikrose** [comment]
We'll welcome you back if you have time later!

**Comment by cantino** [comment]
Nice!
