### ISSUE TITLE
Return an array of nodes?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fathom#38]
I'm trying to play w/ `<meta name="keywords"/>` and using open graph tags... Does Fathom support returning multiple matching elements?

For example, can I return all matching `meta[property='og:video:tag']` elements?

```html
<meta name="keywords" content="&quot;double dream hands&quot; &quot;john jacobson&quot; music dance fun &quot;sprint guy&quot;">
...
<meta property="og:video:tag" content="double dream hands">
<meta property="og:video:tag" content="john jacobson">
<meta property="og:video:tag" content="music">
<meta property="og:video:tag" content="dance">
<meta property="og:video:tag" content="fun">
<meta property="og:video:tag" content="sprint guy">
```

Plus http://ogp.me/#no_vertical

Ultimately, I think we want to return an array of keywords (either from meta keywords, or `og:article:tag`, `og:book:tag`, or `og:video:tag`).

The other use case would be potentially returning an array of `og:image` tags, per http://ogp.me/#array. (Currently ignoring the problem of trying to extract adjacent `og:image` and optional `og:image:width` and `og:image:height` elements):

```html
<meta property="og:image" content="http://example.com/rock.jpg" />
<meta property="og:image:width" content="300" />
<meta property="og:image:height" content="300" />
<meta property="og:image" content="http://example.com/rock2.jpg" />
<meta property="og:image" content="http://example.com/rock3.jpg" />
<meta property="og:image:height" content="1000" />
```

**Comment by pdehaan** [comment]
Plus, those `<meta name="keywords"/>` are invalid (disappointing for a [YouTube page](https://www.youtube.com/user/JhnJacobson)), per the [MDN spec](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta#attr-name) since they aren't comma separated, so technically they're one giant keyword:

> `keywords`, containing, as strings separated by commas, relevant words associated with the content of the page;

**Comment by erikrose** [comment]
Fathom absolutely will return multiple matching nodes: from dom() and type() selectors both. For the og:image and adjacent width and height tag problem, the easiest thing may be to do a dom('...og:image...') selector and then, in the ranker function, walk the tree to the adjacent height/width and pull them in and stick them in a note. Let me know if you need more of a walkthrough, since the docs are still sparse.
