### ISSUE TITLE
examples with nested classes, e.g. microformats2

### ISSUE THREAD

**Issue by tantek** [mozilla/fathom#42]
Just saw the lightning talk at #MozAloha - very cool!

Is it possible to write Fathom rules to detect nested class names? Perhaps even with additional CSS Selector constraints?

Would it be possible to add a simple example rule set for parsing data from nested elements with particular class names?

For example, I'd like to write rules like the nested class name rules for microformats2 parsing:

http://microformats.org/wiki/microformats2-parsing#parse_an_element_for_class_microformats

Or at least rules like:
.h-entry .p-name -> title = textContent

Happy to help get something simple working and iterate from there.

**Comment by tantek** [comment]
cc: @mixedpuppy who may have some suggestions for how to do this in Firefox in particular

**Comment by erikrose** [comment]
Absolutely. For simple cases, you could just use CSS selectors, like...

```
const rules = ruleset(
    rule(dom('.h-entry .p-name'), type('title').note(fnode => fnode.element.textContent))
);
```

Soon I plan to add `contains()` and `matching()` to the left-hand side of rules that will make it easier to express typed containment (a "foo"-typed node within a "title"-typed node) and arbitrary predicates.

**Comment by lusk** [comment]
Yes, `contains()` and `matching()` would be a very powerful addition indeed. Do you think you could maybe roughly outline how would your approach the implementation of those? I take you will probably not add any new features anymore given the project is not very active?

**Comment by erikrose** [comment]
Probably just the naive way to begin with, then optimizing as the need proves itself. Most of the dev work is happening in https://github.com/erikrose/fathom-fox/ at the moment: integrating Fathom development tools into Firefox so we can write rulesets faster and more easily. Then I have some crazy ideas for Fathom 3, which will bring contains, matching, and, indeed, arbitrary predicates.

**Comment by lusk** [comment]
Thanks for your reply, Erik. And many thanks for such a cool piece of software! :)
