### ISSUE TITLE
Add toString() methods for things so error messages are nice.

### ISSUE THREAD

**Issue by erikrose** [mozilla/fathom#47]
Not everything has a toString() yet: rules in particular.

**Comment by ArunaMaurya221B** [comment]
Hey!! Could you elaborate more on this.

**Comment by erikrose** [comment]
When structures like rules complain about their input, they aren't specific enough to tell which rule they're talking about. To find examples, you can pretty much just grep the code for `throw`. Here are a few:

```js
throw new Error(`The right-hand side of a dom() rule failed to specify a type. This means there is no way for its output to be used by later rules. All it specified was ${fact}.`);
```

```js
throw new Error('The left-hand side of a rule() must start with dom(), type(), or and().');
```
