### ISSUE TITLE
Link to readthedocs in readme is wrong

### ISSUE THREAD

**Issue by jdm** [mozilla/fathom#59]
I'm pretty sure the content at https://fathom.readthedocs.io/en/latest/ is unrelated to this library.

**Comment by erikrose** [comment]
You are, of course, correct. I made that change in the midst of setting up Fathom on ReadTheDocs. But that turned out to be incapable of running JSDoc, which is part of our documentation build process. I've moved the docs over to GitHub Pages and fixed the link. Thanks for noticing!

**Comment by erikrose** [comment]
https://mozilla.github.io/fathom/
