### ISSUE TITLE
Use for ebooks

### ISSUE THREAD

**Issue by Immortalin** [mozilla/fathom#63]
Is it possible to use this for `EPUB` files? The EPUB format is a subset of XHTML, zipped and with a bit of metadata thrown in. I am trying to strip out unnecessary content e.g. copyright pages, content pages etc. for conversion of ebooks to audiobooks (where such pages are redundant), is this a suitable use case?

**Comment by erikrose** [comment]
Fathom's current abstractions will be able to help you if your items of interest share boundaries with HTML tags. If every page is just a simple container of text, Fathom probably won't save you much work with the textual analysis yet. But if there is signal in CSS classes and DOM tree structure, Fathom is a good choice.
