### ISSUE TITLE
Export ZEROISH and ONEISH for rulesets

### ISSUE THREAD

**Issue by Osmose** [mozilla/fathom#79]
Over in [fathom-trainees](https://github.com/mozilla/fathom-trainees/blob/master/src/trainees.js) there's a recommendation to return not-quite-0 and not-quite 1 values from rules to accommodate the trainer. Fathom should probably be exporting these as `MIN_SCORE` and `MAX_SCORE` constants for rulesets to use so that they don't have to copy the values themselves.

**Comment by erikrose** [comment]
Probably right. I'm tempted to say the fuzzy-logic stuff is still experimental, but it works so well and has so few downsides (and the project is moving so faster) that we might as well commit. Wherever this lands would also be a natural place for the other bits of boilerplate I want to factor out of fathom-trainees.

**Comment by erikrose** [comment]
The neural-network stuff in 3.0 obviates the need to stay away from 0 and 1, so this is no longer needed.
