### ISSUE TITLE
how to use readability.mjs file without comparing two files ?

### ISSUE THREAD

**Issue by rajbaraiya123** [mozilla/fathom#84]
how to use readability.mjs file without comparing two files(expected and source html files), i want to use it  for fetching textual content from any webpage.

**Comment by erikrose** [comment]
First, get a ruleset by calling tunedContentFnodes(). Then, feed the ruleset your web page, as at http://mozilla.github.io/fathom/using.html#pulling-out-answers. The `out()` rule to pull is 'content'. Be aware, however, that the whole readability module is just a demo to illustrate Fathom's potential brevity. It performs fairly slowly as it stands; it needs earlier pruning and a cheaper distance function. If you choose to try it, I recommend using the new [euclidean()](http://mozilla.github.io/fathom/clustering.html#euclidean) distance metric.

**Comment by erikrose** [comment]
It's already been tuned, at least on a small corpus. So you can use the defaults.
