### ISSUE TITLE
Mozilla Ecosystem for readability, Fathom vs Mercury vs Readability

### ISSUE THREAD

**Issue by se4u** [mozilla/fathom#86]
**This is not an issue with the code but I was downvoted to oblivion when [I posted this question on SO](https://stackoverflow.com/posts/53844224/edit) therefore I am posting here**

There seem to be 3 projects related to readability from Mozilla.

1. https://github.com/mozilla/fathom
2. https://github.com/mozilla/readability
3. https://medium.com/@readability/an-important-announcement-for-all-readability-api-users-32dbee232b29 and https://mercury.postlight.com/

Fathom claims to be a successor of readability but I checked their GitHub repos and both of them are still merging pull requests and recent commits were from less than a month ago. Similarly, the medium article, ostensibly from Mozilla, claims that mercury is a successor for readability. 

Could you clarify the different features of these libraries, please?

**Comment by erikrose** [comment]
Hi. Apologies for the lack of clarity. I don't believe Fathom ever claimed to be the successor to Readability, though it has the potential. When I wrote https://hacks.mozilla.org/2017/04/fathom-a-framework-for-understanding-web-pages/, what I intended to demonstrate was that Fathom delivers brevity wins: specifically, that it could implement something on the same order of accuracy as Readability in a much smaller space. However, have a look at the footnote, which clarifies that future work is needed for a production solution.

Fathom is a more general-purpose library, intended for identifying arbitrary elements of web pages—for example, prices and products for [Price Wise](https://blog.mozilla.org/firefox/price-wise/)—or categorizing entire pages. I'm sure you've already found the introductory material at http://mozilla.github.io/fathom/.

Readability still powers Reader Mode in Firefox.

I can't speak for Mercury and don't know who is behind it.

I hope that helps! Happy new year.
