### ISSUE TITLE
Consider providing a destination directory option for `fathom-unzip`

### ISSUE THREAD

**Issue by biancadanforth** [mozilla/fathom#93]
Currently, `fathom-unzip` unzips to the current working directory. It'd be nice if there were an option to pass in a destination directory.

**Comment by erikrose** [comment]
What do you think of closing the 3 fathom-zip tickets as wontfix? We're no longer giving samples ridiculously long names at collection time, so the tool should no longer even be necessary.

https://github.com/mozilla/fathom/issues/93 (this)
https://github.com/mozilla/fathom/issues/94
https://github.com/mozilla/fathom/issues/95

**Comment by erikrose** [comment]
I'm going to go ahead and close these to clean up the tracker. Feel free to speak up if you have a reason to reopen them.

**Comment by biancadanforth** [comment]
Sorry, must have missed this; that sounds fine to me.
