### ISSUE TITLE
Consider adding prefix option to `fathom-unzip` to avoid filename collisions

### ISSUE THREAD

**Issue by biancadanforth** [mozilla/fathom#94]
It is possible that sample pages exist in multiple different zip files (e.g. pages for Amazon are in an Amazon zip file, pages for Ebay are in an Ebay zip file, etc.). Trying to combine these unzipped, renamed samples into a single directory after running each of the zip files through `fathom-unzip` can result in name collisions (especially when it defaults to place the unzipped and renamed files into the current working directory with no alternative, see #93 ). It'd be helpful if there were a prefix option (or similar) to avoid this issue.

**Comment by erikrose** [comment]
Though consider that our more modern corpora give each sample a unique name, of the format 1.html, 2.html, etc. Hopefully this means the end of collisions, unless we start combining corpora after the fact or something. It is indeed a common need to use [a util](https://www.publicspace.net/ABetterFinderRename/) to batch-rename files, for whatever reason, in the broader world, so you've certainly hit upon a wider pattern.

**Comment by erikrose** [comment]
Closing as per https://github.com/mozilla/fathom/issues/93#issuecomment-567931224.
