### ISSUE TITLE
Consider allowing a space-separated list of zip files as an argument to `fathom-unzip`

### ISSUE THREAD

**Issue by biancadanforth** [mozilla/fathom#95]
It is possible that sample pages exist in multiple different zip files (e.g. pages for Amazon are in an Amazon zip file, pages for Ebay are in an Ebay zip file, etc.). It'd be helpful if `fathom-unzip` accepted a space-separated list of zip files, so that multiple zip files can be unzipped and renamed with a single command; this could optionally automatically prefix the new filenames to avoid filename collisions (related to #94 ).

**Comment by erikrose** [comment]
Closing as per https://github.com/mozilla/fathom/issues/93#issuecomment-567931224.
